[package]
name = "ebur128-compressor"
version = "0.1.0"
authors = ["Pachler, Uwe <uwe.pachler@datagroup.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lv2rs="0.3"

[lib]
crate-type = ["dylib"]


